#!/usr/bin/env python3
"""
TrustVerify – CLI Tool for File Integrity and Digital Signatures
Usage: python trustverify.py <command> [options]
"""

import argparse
import hashlib
import json
import os
import sys

from cryptography.hazmat.primitives import hashes, serialization
from cryptography.hazmat.primitives.asymmetric import rsa, padding
from cryptography.hazmat.backends import default_backend
from cryptography.exceptions import InvalidSignature


# ─────────────────────────────────────────────
#  Core utility
# ─────────────────────────────────────────────

def sha256_file(filepath: str) -> str:
    """Return hex-encoded SHA-256 digest of a file (streaming for large files)."""
    h = hashlib.sha256()
    with open(filepath, "rb") as f:
        for chunk in iter(lambda: f.read(8192), b""):
            h.update(chunk)
    return h.hexdigest()


# ─────────────────────────────────────────────
#  Part 1 – Task 1: Hash a single file
# ─────────────────────────────────────────────

def cmd_hash(args):
    path = args.file
    if not os.path.isfile(path):
        print(f"[ERROR] File not found: {path}")
        sys.exit(1)
    digest = sha256_file(path)
    print(f"SHA-256({path}):")
    print(f"  {digest}")


# ─────────────────────────────────────────────
#  Part 1 – Task 2: Generate Manifest
# ─────────────────────────────────────────────

def cmd_manifest(args):
    directory = args.directory
    if not os.path.isdir(directory):
        print(f"[ERROR] Directory not found: {directory}")
        sys.exit(1)

    manifest = {}
    for root, _, files in os.walk(directory):
        for fname in sorted(files):
            # Skip artifacts generated by this tool
            if fname in ("metadata.json", "signature.bin"):
                continue
            fpath = os.path.join(root, fname)
            rel_path = os.path.relpath(fpath, directory)
            manifest[rel_path] = sha256_file(fpath)

    output_path = os.path.join(directory, "metadata.json")
    with open(output_path, "w") as f:
        json.dump(manifest, f, indent=4)

    print(f"[OK] Manifest created -> {output_path}")
    for rel, digest in manifest.items():
        print(f"     {digest[:16]}...  {rel}")
    print(f"     Total: {len(manifest)} file(s) indexed")


# ─────────────────────────────────────────────
#  Part 1 – Task 3: Check Integrity
# ─────────────────────────────────────────────

def cmd_check(args):
    directory = args.directory
    manifest_path = os.path.join(directory, "metadata.json")

    if not os.path.isfile(manifest_path):
        print(f"[ERROR] metadata.json not found in '{directory}'")
        sys.exit(1)

    with open(manifest_path, "r") as f:
        manifest = json.load(f)

    ok, tampered, missing = [], [], []

    for rel_path, expected_hash in manifest.items():
        fpath = os.path.join(directory, rel_path)
        if not os.path.isfile(fpath):
            missing.append(rel_path)
        else:
            actual_hash = sha256_file(fpath)
            if actual_hash != expected_hash:
                tampered.append((rel_path, expected_hash, actual_hash))
            else:
                ok.append(rel_path)

    print("\n=== TrustVerify Integrity Check ===")
    print(f"  OK       : {len(ok)}")
    print(f"  TAMPERED : {len(tampered)}")
    print(f"  MISSING  : {len(missing)}")

    if missing:
        print("\n[MISSING FILES]")
        for f in missing:
            print(f"  - {f}")

    if tampered:
        print("\n[TAMPERED FILES]")
        for rel, exp, got in tampered:
            print(f"  - {rel}")
            print(f"      expected : {exp}")
            print(f"      actual   : {got}")

    if not missing and not tampered:
        print("\n  PASS - All files are intact. No tampering detected.")
    else:
        print("\n  FAIL - Integrity check FAILED. Data poisoning/tampering detected.")
        sys.exit(2)


# ─────────────────────────────────────────────
#  Part 2 – Task 4: Generate RSA Key Pair
# ─────────────────────────────────────────────

def cmd_keygen(args):
    priv_path = args.private_key or "private_key.pem"
    pub_path  = args.public_key  or "public_key.pem"

    print("[INFO] Generating 2048-bit RSA key pair...")
    private_key = rsa.generate_private_key(
        public_exponent=65537,
        key_size=2048,
        backend=default_backend()
    )

    with open(priv_path, "wb") as f:
        f.write(private_key.private_bytes(
            encoding=serialization.Encoding.PEM,
            format=serialization.PrivateFormat.TraditionalOpenSSL,
            encryption_algorithm=serialization.NoEncryption()
        ))

    public_key = private_key.public_key()
    with open(pub_path, "wb") as f:
        f.write(public_key.public_bytes(
            encoding=serialization.Encoding.PEM,
            format=serialization.PublicFormat.SubjectPublicKeyInfo
        ))

    print(f"[OK] Key pair generated.")
    print(f"     Private key -> {priv_path}  (KEEP SECRET)")
    print(f"     Public key  -> {pub_path}   (share freely)")


# ─────────────────────────────────────────────
#  Part 2 – Task 5: Sign the Manifest
# ─────────────────────────────────────────────

def cmd_sign(args):
    manifest_path = args.manifest
    priv_key_path = args.private_key
    output_path   = args.output or "signature.bin"

    if not os.path.isfile(manifest_path):
        print(f"[ERROR] Manifest not found: {manifest_path}")
        sys.exit(1)
    if not os.path.isfile(priv_key_path):
        print(f"[ERROR] Private key not found: {priv_key_path}")
        sys.exit(1)

    # Step 1: Show the SHA-256 of the manifest (informational)
    manifest_hash_hex = sha256_file(manifest_path)
    print(f"[INFO] Manifest SHA-256 : {manifest_hash_hex}")

    # Step 2: Load private key
    with open(priv_key_path, "rb") as f:
        private_key = serialization.load_pem_private_key(
            f.read(), password=None, backend=default_backend()
        )

    # Step 3: Read manifest bytes and sign
    # RSA-PSS with SHA-256: the library hashes the content internally before signing
    with open(manifest_path, "rb") as f:
        manifest_bytes = f.read()

    signature = private_key.sign(
        manifest_bytes,
        padding.PSS(
            mgf=padding.MGF1(hashes.SHA256()),
            salt_length=padding.PSS.MAX_LENGTH
        ),
        hashes.SHA256()
    )

    with open(output_path, "wb") as f:
        f.write(signature)

    print(f"[OK] Signature written  -> {output_path}  ({len(signature)} bytes)")
    print(f"     Share with receiver: metadata.json + {output_path} + public_key.pem")


# ─────────────────────────────────────────────
#  Part 2 – Task 6: Verify the Manifest
# ─────────────────────────────────────────────

def cmd_verify(args):
    manifest_path  = args.manifest
    signature_path = args.signature
    pub_key_path   = args.public_key

    for p in [manifest_path, signature_path, pub_key_path]:
        if not os.path.isfile(p):
            print(f"[ERROR] File not found: {p}")
            sys.exit(1)

    print("\n=== TrustVerify Signature Verifier ===")

    # Step 1: Show hash of the manifest received
    manifest_hash_hex = sha256_file(manifest_path)
    print(f"  Manifest SHA-256 : {manifest_hash_hex}")

    # Step 2: Load public key
    with open(pub_key_path, "rb") as f:
        public_key = serialization.load_pem_public_key(f.read(), backend=default_backend())

    # Step 3: Load signature
    with open(signature_path, "rb") as f:
        signature = f.read()

    # Step 4: Load manifest bytes
    with open(manifest_path, "rb") as f:
        manifest_bytes = f.read()

    # Step 5: Verify
    try:
        public_key.verify(
            signature,
            manifest_bytes,
            padding.PSS(
                mgf=padding.MGF1(hashes.SHA256()),
                salt_length=padding.PSS.MAX_LENGTH
            ),
            hashes.SHA256()
        )
        print("\n  SIGNATURE VALID")
        print("  -> Manifest is authentic and has NOT been tampered with.")
        print("  -> Confirmed to originate from the holder of the private key.")
    except InvalidSignature:
        print("\n  SIGNATURE INVALID")
        print("  -> Manifest has been TAMPERED with, or wrong public key used.")
        print("  -> Do NOT trust this manifest.")
        sys.exit(3)


# ─────────────────────────────────────────────
#  CLI Entry Point
# ─────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        prog="trustverify",
        description="TrustVerify - File Integrity & Digital Signature CLI Tool",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python trustverify.py hash document.pdf
  python trustverify.py manifest ./files
  python trustverify.py check ./files
  python trustverify.py keygen --private-key alice_priv.pem --public-key alice_pub.pem
  python trustverify.py sign --manifest ./files/metadata.json --private-key alice_priv.pem
  python trustverify.py verify --manifest ./files/metadata.json --signature signature.bin --public-key alice_pub.pem
        """
    )
    sub = parser.add_subparsers(dest="command", metavar="<command>")
    sub.required = True

    # hash
    p_hash = sub.add_parser("hash", help="Compute SHA-256 of a file")
    p_hash.add_argument("file", help="Path to the file")
    p_hash.set_defaults(func=cmd_hash)

    # manifest
    p_manifest = sub.add_parser("manifest", help="Generate metadata.json for a directory")
    p_manifest.add_argument("directory", help="Target directory")
    p_manifest.set_defaults(func=cmd_manifest)

    # check
    p_check = sub.add_parser("check", help="Verify file integrity against metadata.json")
    p_check.add_argument("directory", help="Directory containing files + metadata.json")
    p_check.set_defaults(func=cmd_check)

    # keygen
    p_keygen = sub.add_parser("keygen", help="Generate RSA 2048-bit key pair")
    p_keygen.add_argument("--private-key", default="private_key.pem", metavar="PATH",
                          help="Output path for private key (default: private_key.pem)")
    p_keygen.add_argument("--public-key",  default="public_key.pem",  metavar="PATH",
                          help="Output path for public key  (default: public_key.pem)")
    p_keygen.set_defaults(func=cmd_keygen)

    # sign
    p_sign = sub.add_parser("sign", help="Sign metadata.json with your private key")
    p_sign.add_argument("--manifest",    required=True, metavar="PATH",
                        help="Path to metadata.json")
    p_sign.add_argument("--private-key", required=True, metavar="PATH",
                        help="Path to sender's private key PEM")
    p_sign.add_argument("--output",      default="signature.bin", metavar="PATH",
                        help="Output signature file (default: signature.bin)")
    p_sign.set_defaults(func=cmd_sign)

    # verify
    p_verify = sub.add_parser("verify", help="Verify manifest authenticity using sender's public key")
    p_verify.add_argument("--manifest",   required=True, metavar="PATH",
                          help="Path to metadata.json")
    p_verify.add_argument("--signature",  required=True, metavar="PATH",
                          help="Path to signature.bin")
    p_verify.add_argument("--public-key", required=True, metavar="PATH",
                          help="Path to sender's public key PEM")
    p_verify.set_defaults(func=cmd_verify)

    args = parser.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
